language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: 'Frontend Tests'
      script: 
        - cd frontend
        - npm install
        - npm run test